export default [
  {
    "type": "Compulsory",
    "id": "Law2213",
    "section": "FR01A",
    "title": "Civil Procedure",
    "selection": "Ballot",
    "instructor": "TBD",
    "exam": "Yes",
    "paper": "No",
    "tclass": "Tu,Th 12:30-2",
    "texam": "5 Morn",
    "term": "FALL"
  },
  {
    "type": "Compulsory",
    "id": "Law2223",
    "section": "FR01A",
    "title": "Commercial Law",
    "selection": "Ballot",
    "instructor": "N Siebrasse",
    "exam": "Yes",
    "paper": "No",
    "tclass": "M,W 11:30-1",
    "texam": "6 Morn",
    "term": "FALL"
  },
  {
    "type": "Compulsory",
    "id": "Law2223",
    "section": "FR01A",
    "title": "Commercial Law",
    "selection": "Ballot",
    "instructor": "J Williamson",
    "exam": "Yes",
    "paper": "No",
    "tclass": "Tu,Th 10-11:30",
    "texam": "6 Morn",
    "term": "FALL"
  },
  {
    "type": "Compulsory",
    "id": "Law2243",
    "section": "FR01A",
    "title": "Evidence",
    "selection": "Ballot",
    "instructor": "N O'Byrne",
    "exam": "Yes",
    "paper": "No",
    "tclass": "M,W 10-11:30",
    "texam": "3 Morn",
    "term": "FALL"
  },
  {
    "type": "Compulsory",
    "id": "Law2253",
    "section": "FR01A",
    "title": "Administrative Law",
    "selection": "Ballot",
    "instructor": "M Marin",
    "exam": "Yes",
    "paper": "No",
    "tclass": "Tu,Th 2-3:30",
    "texam": "8 Morn",
    "term": "FALL"
  },
  {
    "type": "Compulsory",
    "id": "Law2273",
    "section": "FR01A",
    "title": "Business Organizations",
    "selection": "Ballot",
    "instructor": "V Urinov",
    "exam": "Yes",
    "paper": "No",
    "tclass": "M,W 1-2:30",
    "texam": "1 Morn",
    "term": "FALL"
  },
  {
    "type": "Compulsory",
    "id": "Law2313",
    "section": "FR01A",
    "title": "Professional Conduct",
    "selection": "Ballot",
    "instructor": "TBD",
    "exam": "Yes",
    "paper": "No",
    "tclass": "Tu,Th 10-11:30",
    "texam": "7 Morn",
    "term": "FALL"
  },
  {
    "type": "Compulsory",
    "id": "Law2323",
    "section": "FR01A",
    "title": "Conflict of Laws",
    "selection": "Ballot",
    "instructor": "J McEvoy",
    "exam": "Yes",
    "paper": "No",
    "tclass": "M,W 1-2:30",
    "texam": "1 Morn",
    "term": "FALL"
  },
  {
    "type": "Seminar",
    "id": "Law3423",
    "section": "FR01A",
    "title": "Legal History: Private Law Since 1700",
    "selection": "Ballot",
    "instructor": "K Pearlston",
    "exam": "Yes",
    "paper": "Opt",
    "tclass": "Tu,Th 12:30-2",
    "texam": "5 Morn",
    "term": "FALL"
  },
  {
    "type": "Seminar",
    "id": "Law3811",
    "section": "FR01A",
    "title": "SLT: Private Law and Social Justice",
    "selection": "Ballot",
    "instructor": "J Thomson",
    "exam": "No",
    "paper": "Yes",
    "tclass": "M,W 2:30-4",
    "texam": "N/A",
    "term": "FALL"
  },
  {
    "type": "Seminar",
    "id": "Law3815",
    "section": "FR01A",
    "title": "SLT: Wrongful Convictions",
    "selection": "Ballot",
    "instructor": "TBD",
    "exam": "No",
    "paper": "Yes",
    "tclass": "Tu 3:30-6:30",
    "texam": "N/A",
    "term": "FALL"
  },
  {
    "type": "Seminar",
    "id": "Law3908",
    "section": "FR01A",
    "title": "Human Rights",
    "selection": "Ballot",
    "instructor": "A Gough Farnworth",
    "exam": "No",
    "paper": "Yes",
    "tclass": "M 6-9",
    "texam": "N/A",
    "term": "FALL"
  },
  {
    "type": "Seminar",
    "id": "Law4013",
    "section": "FR01A",
    "title": "Maritime Law",
    "selection": "Ballot",
    "instructor": "TBD",
    "exam": "No",
    "paper": "Yes",
    "tclass": "Th 6-9",
    "texam": "N/A",
    "term": "FALL"
  },
  {
    "type": "Seminar",
    "id": "Law4023",
    "section": "FR01A",
    "title": "Children's Law",
    "selection": "Ballot",
    "instructor": "TBD",
    "exam": "No",
    "paper": "Yes",
    "tclass": "Th 6-9",
    "texam": "N/A",
    "term": "FALL"
  },
  {
    "type": "Seminar",
    "id": "Law4043",
    "section": "FR01A",
    "title": "Prosecution & Defence of Homicide",
    "selection": "Ballot",
    "instructor": "TBD",
    "exam": "Yes",
    "paper": "No",
    "tclass": "W 6-9",
    "texam": "6 Aft",
    "term": "FALL"
  },
  {
    "type": "Seminar",
    "id": "Law4073",
    "section": "FR01A",
    "title": "Advanced Constitutional Law",
    "selection": "Ballot",
    "instructor": "K Froc",
    "exam": "No",
    "paper": "Yes",
    "tclass": "Tu,Th 3:30-5",
    "texam": "N/A",
    "term": "FALL"
  },
  {
    "type": "Seminar",
    "id": "Law4094",
    "section": "FR01A",
    "title": "Negotiations",
    "selection": "Ballot",
    "instructor": "F Beaulieu",
    "exam": "No",
    "paper": "No",
    "tclass": "Tu 6:30-9:30",
    "texam": "N/A",
    "term": "FALL"
  },
  {
    "type": "Seminar",
    "id": "Law4103",
    "section": "FR01A",
    "title": "Dispute Resolution",
    "selection": "Ballot",
    "instructor": "S Wells",
    "exam": "No",
    "paper": "No",
    "tclass": "M 6-9",
    "texam": "N/A",
    "term": "FALL"
  },
  {
    "type": "Seminar",
    "id": "Law4183",
    "section": "FR01A",
    "title": "Trial Practice",
    "selection": "Ballot",
    "instructor": "E Desmond",
    "exam": "No",
    "paper": "No",
    "tclass": "Tu 5-8",
    "texam": "N/A",
    "term": "FALL"
  },
  {
    "type": "Seminar",
    "id": "Law4193",
    "section": "FR01A",
    "title": "Aboriginal Peoples and Law",
    "selection": "Ballot",
    "instructor": "N O'Byrne",
    "exam": "Yes",
    "paper": "No",
    "tclass": "M,W 2:30-4",
    "texam": "4 Morn",
    "term": "FALL"
  },
  {
    "type": "Application",
    "id": "Law5113",
    "section": "FR01A",
    "title": "Judicial Internship",
    "selection": "Application",
    "instructor": "Associate Dean",
    "exam": "No",
    "paper": "No",
    "tclass": "N/A",
    "texam": "N/A",
    "term": "FALL"
  },
  {
    "type": "Application",
    "id": "Law5124",
    "section": "FR01A",
    "title": "Public Interest Org. Internship",
    "selection": "Application",
    "instructor": "Associate Dean",
    "exam": "No",
    "paper": "No",
    "tclass": "N/A",
    "texam": "N/A",
    "term": "FALL"
  },
  {
    "type": "Application",
    "id": "Law5143",
    "section": "FR01A",
    "title": "Public Prosecutions Internship",
    "selection": "Application",
    "instructor": "Associate Dean",
    "exam": "No",
    "paper": "No",
    "tclass": "N/A",
    "texam": "N/A",
    "term": "FALL"
  },
  {
    "type": "Application",
    "id": "Law5210",
    "section": "FR01X",
    "title": "Community Clinic Course",
    "selection": "Application",
    "instructor": "TBD",
    "exam": "No",
    "paper": "No",
    "tclass": "W 2:30-5:30",
    "texam": "N/A",
    "term": "FALL"
  },
  {
    "type": "Approval",
    "id": "Law4093",
    "section": "FR01A",
    "title": "Directed Research",
    "selection": "Approval",
    "instructor": "Supervisor",
    "exam": "No",
    "paper": "Opt",
    "tclass": "N/A",
    "texam": "N/A",
    "term": "FALL"
  },
  {
    "type": "Approval",
    "id": "Law5083",
    "section": "FR01A",
    "title": "Readings in Legal Theory",
    "selection": "Approval",
    "instructor": "Supervisor",
    "exam": "No",
    "paper": "No",
    "tclass": "N/A",
    "texam": "N/A",
    "term": "FALL"
  },
  {
    "type": "Other",
    "id": "Law3013",
    "section": "FR01A",
    "title": "Bankruptcy and Receivership",
    "selection": "eServices",
    "instructor": "J Williamson",
    "exam": "Yes",
    "paper": "No",
    "tclass": "Tu,Th 12:30-2",
    "texam": "5 Morn",
    "term": "FALL"
  },
  {
    "type": "Other",
    "id": "Law3063",
    "section": "FR01A",
    "title": "Insurance",
    "selection": "Ballot",
    "instructor": "TBD",
    "exam": "Yes",
    "paper": "No",
    "tclass": "Tu,Th 2-3:30",
    "texam": "8 Morn",
    "term": "FALL"
  },
  {
    "type": "Other",
    "id": "Law3133",
    "section": "FR01A",
    "title": "Trusts",
    "selection": "eServices",
    "instructor": "D Klinck",
    "exam": "Yes",
    "paper": "No",
    "tclass": "M,W 11:30-1",
    "texam": "2 Morn",
    "term": "FALL"
  },
  {
    "type": "Other",
    "id": "Law3143",
    "section": "FR01A",
    "title": "Personal Taxation",
    "selection": "eServices",
    "instructor": "V Urinov",
    "exam": "Yes",
    "paper": "No",
    "tclass": "Tu,Th 8:30-10",
    "texam": "7 Aft",
    "term": "FALL"
  },
  {
    "type": "Other",
    "id": "Law3233",
    "section": "FR01A",
    "title": "Real Estate Transactions",
    "selection": "Ballot",
    "instructor": "TBD",
    "exam": "Yes",
    "paper": "No",
    "tclass": "Tu 6:30-9:30",
    "texam": "4 Aft",
    "term": "FALL"
  },
  {
    "type": "Other",
    "id": "Law3453",
    "section": "FR01A",
    "title": "Intellectual Property",
    "selection": "eServices",
    "instructor": "N Siebrasse",
    "exam": "Yes",
    "paper": "No",
    "tclass": "M,W 2:30-4",
    "texam": "4 Morn",
    "term": "FALL"
  },
  {
    "type": "Other",
    "id": "Law3473",
    "section": "FR01A",
    "title": "Health Law",
    "selection": "eServices",
    "instructor": "H Young",
    "exam": "No",
    "paper": "Opt",
    "tclass": "Tu,Th 3:30-5",
    "texam": "N/A",
    "term": "FALL"
  },
  {
    "type": "Other",
    "id": "Law3573",
    "section": "FR01A",
    "title": "Criminal Procedure",
    "selection": "eServices",
    "instructor": "TBD",
    "exam": "Yes",
    "paper": "No",
    "tclass": "M 6-9",
    "texam": "2 Aft",
    "term": "FALL"
  },
  {
    "type": "Other",
    "id": "Law3653",
    "section": "FR01A",
    "title": "Labour Law",
    "selection": "eServices",
    "instructor": "A Gough Farnworth",
    "exam": "No",
    "paper": "Yes",
    "tclass": "W 6-9",
    "texam": "N/A",
    "term": "FALL"
  },
  {
    "type": "Other",
    "id": "Law3763",
    "section": "FR01A",
    "title": "International Law and Organizations",
    "selection": "eServices",
    "instructor": "A W La Forest",
    "exam": "Yes",
    "paper": "No",
    "tclass": "M,W 10-11:30",
    "texam": "3 Morn",
    "term": "FALL"
  },
  {
    "type": "Other",
    "id": "Law4053",
    "section": "FR01A",
    "title": "Community Planning",
    "selection": "eServices",
    "instructor": "TBD",
    "exam": "Yes",
    "paper": "No",
    "tclass": "W 6-9",
    "texam": "5 Aft",
    "term": "FALL"
  },
  {
    "type": "Compulsory",
    "id": "Law2213",
    "section": "FR01B",
    "title": "Civil Procedure",
    "selection": "Ballot",
    "instructor": "TBD",
    "exam": "Yes",
    "paper": "No",
    "tclass": "M 6-9",
    "texam": "7 Morn",
    "term": "WINTER"
  },
  {
    "type": "Compulsory",
    "id": "Law2243",
    "section": "FR01B",
    "title": "Evidence",
    "selection": "Ballot",
    "instructor": "TBD",
    "exam": "Yes",
    "paper": "No",
    "tclass": "M,W 10-11:30",
    "texam": "1 Morn",
    "term": "WINTER"
  },
  {
    "type": "Compulsory",
    "id": "Law2253",
    "section": "FR01B",
    "title": "Administrative Law",
    "selection": "Ballot",
    "instructor": "K Froc",
    "exam": "Yes",
    "paper": "No",
    "tclass": "Tu,Th 2-3:30",
    "texam": "5 Morn",
    "term": "WINTER"
  },
  {
    "type": "Compulsory",
    "id": "Law2273",
    "section": "FR01B",
    "title": "Business Organizations",
    "selection": "Ballot",
    "instructor": "M Marin",
    "exam": "Yes",
    "paper": "No",
    "tclass": "Tu,Th 10-11:30",
    "texam": "3 Morn",
    "term": "WINTER"
  },
  {
    "type": "Compulsory",
    "id": "Law2313",
    "section": "FR01B",
    "title": "Professional Conduct",
    "selection": "Ballot",
    "instructor": "J Kleefeld",
    "exam": "Yes",
    "paper": "No",
    "tclass": "Tu,Th 8:30-10",
    "texam": "1 Morn",
    "term": "WINTER"
  },
  {
    "type": "Compulsory",
    "id": "Law2323",
    "section": "FR01B",
    "title": "Conflict of Laws",
    "selection": "Ballot",
    "instructor": "A W La Forest",
    "exam": "Yes",
    "paper": "No",
    "tclass": "Tu,Th 2-3:30",
    "texam": "5 Morn",
    "term": "WINTER"
  },
  {
    "type": "Seminar",
    "id": "Law3809",
    "section": "FR01B",
    "title": "SLT: Aboriginal Self-Government & Economic Development",
    "selection": "Ballot",
    "instructor": "N O'Byrne",
    "exam": "No",
    "paper": "Yes",
    "tclass": "M,W 1-2:30",
    "texam": "N/A",
    "term": "WINTER"
  },
  {
    "type": "Seminar",
    "id": "Law3810",
    "section": "FR01B",
    "title": "SLT: Advanced Evidence",
    "selection": "Ballot",
    "instructor": "N O'Byrne",
    "exam": "No",
    "paper": "Yes",
    "tclass": "M,W 10-11:30",
    "texam": "N/A",
    "term": "WINTER"
  },
  {
    "type": "Seminar",
    "id": "Law3812",
    "section": "FR01B",
    "title": "SLT: Cybercrime",
    "selection": "Ballot",
    "instructor": "J Austin",
    "exam": "No",
    "paper": "Yes",
    "tclass": "Tu,Th 3:30-5",
    "texam": "N/A",
    "term": "WINTER"
  },
  {
    "type": "Seminar",
    "id": "Law3813",
    "section": "FR01B",
    "title": "SLT: Commercial Insolvency",
    "selection": "Ballot",
    "instructor": "TBD",
    "exam": "Yes",
    "paper": "No",
    "tclass": "Tu,Th 12:30-2",
    "texam": "4 Aft",
    "term": "WINTER"
  },
  {
    "type": "Seminar",
    "id": "Law4094",
    "section": "FR01B",
    "title": "Negotiations",
    "selection": "Ballot",
    "instructor": "F Beaulieu",
    "exam": "No",
    "paper": "No",
    "tclass": "Tu 6:30-9:30",
    "texam": "N/A",
    "term": "WINTER"
  },
  {
    "type": "Seminar",
    "id": "Law4103",
    "section": "FR01B",
    "title": "Dispute Resolution",
    "selection": "Ballot",
    "instructor": "E Desmond",
    "exam": "No",
    "paper": "No",
    "tclass": "Tu 5-8",
    "texam": "N/A",
    "term": "WINTER"
  },
  {
    "type": "Seminar",
    "id": "Law4163",
    "section": "FR01B",
    "title": "Law & Social Justice",
    "selection": "Ballot",
    "instructor": "TBD",
    "exam": "No",
    "paper": "Yes",
    "tclass": "M 6-9",
    "texam": "N/A",
    "term": "WINTER"
  },
  {
    "type": "Seminar",
    "id": "Law4183",
    "section": "FR01B",
    "title": "Trial Practice",
    "selection": "Ballot",
    "instructor": "TBD",
    "exam": "No",
    "paper": "No",
    "tclass": "W 6-9",
    "texam": "N/A",
    "term": "WINTER"
  },
  {
    "type": "Application",
    "id": "Law5113",
    "section": "FR01B",
    "title": "Judicial Internship",
    "selection": "Application",
    "instructor": "Associate Dean",
    "exam": "No",
    "paper": "No",
    "tclass": "N/A",
    "texam": "N/A",
    "term": "WINTER"
  },
  {
    "type": "Application",
    "id": "Law5123",
    "section": "FR01B",
    "title": "Attorney-General Internship",
    "selection": "Application",
    "instructor": "Associate Dean",
    "exam": "No",
    "paper": "No",
    "tclass": "N/A",
    "texam": "N/A",
    "term": "WINTER"
  },
  {
    "type": "Application",
    "id": "Law5143",
    "section": "FR01B",
    "title": "Public Prosecutions Internship",
    "selection": "Application",
    "instructor": "Associate Dean",
    "exam": "No",
    "paper": "No",
    "tclass": "N/A",
    "texam": "N/A",
    "term": "WINTER"
  },
  {
    "type": "Application",
    "id": "Law5210",
    "section": "FR01Y",
    "title": "Community Clinic Course",
    "selection": "Application",
    "instructor": "TBD",
    "exam": "No",
    "paper": "No",
    "tclass": "N/A",
    "texam": "N/A",
    "term": "WINTER"
  },
  {
    "type": "Approval",
    "id": "Law4093",
    "section": "FR01B",
    "title": "Directed Research",
    "selection": "Approval",
    "instructor": "Supervisor",
    "exam": "No",
    "paper": "Opt",
    "tclass": "N/A",
    "texam": "N/A",
    "term": "WINTER"
  },
  {
    "type": "Approval",
    "id": "Law5083",
    "section": "FR01B",
    "title": "Readings in Legal Theory",
    "selection": "Approval",
    "instructor": "Supervisor",
    "exam": "No",
    "paper": "No",
    "tclass": "N/A",
    "texam": "N/A",
    "term": "WINTER"
  },
  {
    "type": "Other",
    "id": "Law3043",
    "section": "FR01B",
    "title": "Remedies",
    "selection": "eServices",
    "instructor": "N Siebrasse",
    "exam": "Yes",
    "paper": "No",
    "tclass": "M,W 2:30-4",
    "texam": "2 Morn",
    "term": "WINTER"
  },
  {
    "type": "Other",
    "id": "Law3113",
    "section": "FR01B",
    "title": "Corporate Finance",
    "selection": "eServices",
    "instructor": "V Urinov",
    "exam": "Yes",
    "paper": "No",
    "tclass": "M,W 11:30-1",
    "texam": "6 Morn",
    "term": "WINTER"
  },
  {
    "type": "Other",
    "id": "Law3123",
    "section": "FR01B",
    "title": "Immigration Law",
    "selection": "eServices",
    "instructor": "TBD",
    "exam": "Yes",
    "paper": "No",
    "tclass": "Tu 4-7",
    "texam": "8 Morn",
    "term": "WINTER"
  },
  {
    "type": "Other",
    "id": "Law3153",
    "section": "FR01B",
    "title": "Corporate Taxation",
    "selection": "eServices",
    "instructor": "V Urinov",
    "exam": "Yes",
    "paper": "No",
    "tclass": "Tu,Th 10-11:30",
    "texam": "3 Morn",
    "term": "WINTER"
  },
  {
    "type": "Other",
    "id": "Law3293",
    "section": "FR01B",
    "title": "Wills & Estate Succession",
    "selection": "eServices",
    "instructor": "J Thomson",
    "exam": "Yes",
    "paper": "No",
    "tclass": "M,W 2:30-4",
    "texam": "2 Morn",
    "term": "WINTER"
  },
  {
    "type": "Other",
    "id": "Law3353",
    "section": "FR01B",
    "title": "Family Law",
    "selection": "eServices",
    "instructor": "K Pearlston",
    "exam": "Yes",
    "paper": "No",
    "tclass": "M,W 1-2:30",
    "texam": "4 Morn",
    "term": "WINTER"
  },
  {
    "type": "Other",
    "id": "Law3454",
    "section": "FR01B",
    "title": "Environmental Law",
    "selection": "eServices",
    "instructor": "TBD",
    "exam": "No",
    "paper": "Opt",
    "tclass": "Th 6-9",
    "texam": "N/A",
    "term": "WINTER"
  },
  {
    "type": "Other",
    "id": "Law3683",
    "section": "FR01B",
    "title": "Employment Law",
    "selection": "Ballot",
    "instructor": "TBD",
    "exam": "No",
    "paper": "No",
    "tclass": "M 6-9",
    "texam": "N/A",
    "term": "WINTER"
  },
  {
    "type": "Other",
    "id": "Law3723",
    "section": "FR01B",
    "title": "Law and Economics/ECON3845",
    "selection": "eServices",
    "instructor": "T McDonald",
    "exam": "Yes",
    "paper": "No",
    "tclass": "M,W 8:30-10",
    "texam": "2 Aft",
    "term": "WINTER"
  },
  {
    "type": "Seminar",
    "id": "Law3814",
    "section": "FR01B",
    "title": "SLT: Patent Law",
    "selection": "eServices",
    "instructor": "N Siebrasse",
    "exam": "Yes",
    "paper": "No",
    "tclass": "M,W 11:30-1",
    "texam": "6 Morn",
    "term": "WINTER"
  },
  {
    "type": "Other",
    "id": "Law3933",
    "section": "FR01B",
    "title": "Jurisprudence",
    "selection": "eServices",
    "instructor": "J Hughes",
    "exam": "Yes",
    "paper": "Opt",
    "tclass": "M,W 4-5:30",
    "texam": "8 Aft",
    "term": "WINTER"
  }
]
